/*! theodyx-r2media v1.2.0 - C-02: the touch hero height is a min-height floor, not a hard cap, so a tall
   title can no longer push itself up under the nav pill (see the comment inline below).
   1.1.0 - re-hosted from Webflow on 2026-09-05; source of truth is now this repo */
(function(){var C=[].slice.call(document.querySelectorAll('.ethx-imgsrc'));C.forEach(function(c){var u=(c.textContent||'').trim();if(!/^https:\/\//.test(u))return;var scope=c.classList.contains('ethx-imgsrc-divider')?document.querySelector('.ethx-divider'):document.querySelector('.ethx-hero');if(!scope)return;var img=scope.querySelector('img.ethx-media');if(!img){img=document.createElement('img');img.className='ethx-media';img.alt='';scope.insertBefore(img,scope.firstChild)}img.removeAttribute('srcset');img.removeAttribute('sizes');img.src=u;img.loading='eager';img.setAttribute('fetchpriority','high');img.decoding='async';img.classList.remove('w-dyn-bind-empty');img.classList.add('xp-r2');img.style.removeProperty('display')})})();
(function(){try{var T=false;try{T=matchMedia('(pointer: coarse)').matches}catch(e){}if(!T)T=(navigator.maxTouchPoints||0)>0||('ontouchstart' in window);if(!T)return;document.documentElement.classList.add('xp-touch');[].forEach.call(document.querySelectorAll('.ethx-hero,.ethx-divider'),function(el){el.style.setProperty('position','relative','important');el.style.setProperty('top','auto','important');/* C-02: the hero is a FLOOR, not a cap. It used to be pinned to height:72svh inline-important, which
   no stylesheet can outrank, so when the title + dek + jump arrow were taller than 72svh the
   bottom-aligned .ethx-heroinner overflowed its start edge and slid the H1 up under the nav pill.
   min-height keeps the same 72svh stage on every viewport where the content fits, and lets the hero
   grow instead of clipping where it does not. The divider carries no text, so it stays pinned. */if(el.classList.contains('ethx-hero')){el.style.setProperty('height','auto','important');el.style.setProperty('min-height','72vh','important');el.style.setProperty('min-height','72svh','important')}else{el.style.setProperty('height','72vh','important');el.style.setProperty('height','72svh','important')}});[].forEach.call(document.querySelectorAll('.ethx-hero img.ethx-media,.ethx-hero video.ethx-media,.ethx-divider img'),function(el){el.style.setProperty('animation','none','important');el.style.setProperty('transform','none','important')});[].forEach.call(document.querySelectorAll('.ethx-heroinner > *'),function(el){el.style.setProperty('animation','none','important')})}catch(e){}})();/*thx-r2media-1.2.0*/
