/*! theodyx-stories 1.3.0 (2026-09-11): featured stories are not repeated in the grid; empty band hidden; tab anchors resolve */
(function(){function q(s,r){return [].slice.call((r||document).querySelectorAll(s))}q('.thx-rel-slug').forEach(function(s){var a=s.closest('a');var t=s.textContent.trim();if(!a||!t)return;var h=a.getAttribute('href');if(h!=='/our-thinking'&&h!=='#')return;a.setAttribute('href',(s.classList.contains('ethx-slug')?'/index/':'/our-thinking/')+t)});var L=document.querySelector('.thxo-storygrid');if(!L)return;var C=q(':scope>div',L),N=12,n=N,cat='',asc=0;
/* 1.3.0 (2026-09-11, owner): the four featured stories no longer repeat below the fold - any card whose link is already in the
   featured rail leaves the story grid and the Features band; a band left with no cards is hidden with its heading (the lone
   Ethos card + dead white space); the rail's filter tabs point at the story grid so the fragment resolves for keyboard / no-JS. */
try{var FEAT={};q('.thxo-featgrid a[href]').forEach(function(a){FEAT[a.getAttribute('href')]=1});
  var hrefOf=function(c){var a=c.matches&&c.matches('a[href]')?c:c.querySelector('a[href]');return a?a.getAttribute('href'):''};
  C=C.filter(function(c){if(FEAT[hrefOf(c)]){c.parentNode.removeChild(c);return false}return true});
  q('.thxo-grid4').forEach(function(g){q(':scope>*',g).forEach(function(c){if(FEAT[hrefOf(c)])c.parentNode.removeChild(c)});if(!g.children.length){var sec=g.closest('section,.thxo-sec');(sec&&sec!==L.closest('section,.thxo-sec')?sec:g.closest('.w-dyn-list')||g).style.display='none'}});
  var sec2=L.closest('section,.thxo-sec');if(sec2&&!sec2.id)sec2.id='thxo-stories';q('.thxo-tab[href^="#"]').forEach(function(t){t.setAttribute('href','#'+(sec2&&sec2.id||'thxo-stories'))});
}catch(e){}
var M=document.getElementById('thxo-more');function T(c){var p=c.querySelector('.thxo-meta-cat');return p?p.textContent.trim():''}function D(c){var ps=q('.thxo-meta-i',c);var t=ps[1]?ps[1].textContent:'';var d=Date.parse(t);return isNaN(d)?0:d}function A(){var v=C.filter(function(c){return !cat||T(c)===cat});v.sort(function(a,b){return asc?D(a)-D(b):D(b)-D(a)});v.forEach(function(c){L.appendChild(c)});C.forEach(function(c){c.style.display='none'});v.slice(0,n).forEach(function(c){c.style.display=''});if(M)M.style.display=v.length>n?'':'none'}q('.thxo-tab').forEach(function(t){t.addEventListener('click',function(e){e.preventDefault();q('.thxo-tab').forEach(function(x){x.classList.remove('thxo-tab-on')});t.classList.add('thxo-tab-on');cat=t.getAttribute('data-cat')||'';n=N;A()})});if(M)M.addEventListener('click',function(e){e.preventDefault();n+=N;A()});var S=document.getElementById('thxo-sort');if(S)S.addEventListener('click',function(e){e.preventDefault();asc=asc?0:1;S.textContent='Sort: '+(asc?'Oldest':'Newest');A()});var G=document.getElementById('thxo-view-grid'),V=document.getElementById('thxo-view-list');function W(l){if(G&&V){V.classList.toggle('thxo-ctrl-on',!!l);G.classList.toggle('thxo-ctrl-on',!l)}L.style.gridTemplateColumns=l?'1fr':'';L.style.rowGap=l?'28px':'';q('.thxo-media',L).forEach(function(m){m.style.display=l?'none':''})}if(G)G.addEventListener('click',function(e){e.preventDefault();W(0)});if(V)V.addEventListener('click',function(e){e.preventDefault();W(1)});A()})();