// Phase 11 motion verifier. Usage: node p11_verify.js [--prod]  (staging by default; fresh context per page; GPU flags for the nav)
const { chromium, devices } = require('playwright');
const fs = require('fs'), path = require('path');
const PROD = process.argv.includes('--prod'); const BASE = PROD ? 'https://www.theodyx.com' : 'https://nhq.webflow.io';
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36';
const results = []; let fails = 0;
const check = (name, ok, detail) => { results.push({ name, ok: !!ok, detail }); if (!ok) fails++; console.log((ok ? 'PASS ' : 'FAIL ') + name + (detail !== undefined ? ' — ' + (typeof detail === 'string' ? detail : JSON.stringify(detail)).slice(0, 300) : '')); };
const sleep = ms => new Promise(r => setTimeout(r, ms));
const SPRING = /cubic-bezier\(0\.22, 1, 0\.36, 1\)/;
(async () => {
  const browser = await chromium.launch({ headless: true, args: ['--enable-gpu', '--use-angle=metal', '--ignore-gpu-blocklist'] });
  async function open(p, opts = {}) { const ctx = await browser.newContext(Object.assign({ viewport: { width: 1440, height: 900 }, userAgent: UA }, opts.ctx || {})); const page = await ctx.newPage(); const errors = []; page.on('pageerror', e => errors.push(String(e))); page.on('console', m => { if (m.type() === 'error' && !/challenges\.cloudflare|cdn-cgi|turnstile|status of 404/i.test(m.text() + (m.location() && m.location().url))) errors.push(m.text()); }); if (opts.init) await page.addInitScript(opts.init); await page.goto(BASE + p, { waitUntil: 'load' }); await sleep(opts.settle || 1800); return { page, ctx, errors }; }
  // animation recorder via CDP: count animations started during a scroll, excluding the nav and the hero
  const ANIM_INIT = () => { window.__anims = []; const orig = Element.prototype.animate; Element.prototype.animate = function () { window.__anims.push({ sel: (this.className || this.tagName || '').toString().slice(0, 40), via: 'waapi' }); return orig.apply(this, arguments); }; document.addEventListener('transitionstart', e => { const t = e.target; if (!(t instanceof Element)) return; if (t.closest('#thx-nav, .thx-skip, .thxck-banner, .thxck-modal, .thxck-overlay')) return; window.__anims.push({ sel: (t.className || t.tagName || '').toString().slice(0, 40), prop: e.propertyName, via: 'transition' }); }, true); document.addEventListener('animationstart', e => { const t = e.target; if (!(t instanceof Element)) return; if (t.closest('#thx-nav')) return; window.__anims.push({ sel: (t.className || t.tagName || '').toString().slice(0, 40), prop: e.animationName, via: 'animation' }); }, true); };
  async function scrollAll(page) { await page.evaluate(async () => { const h = document.documentElement.scrollHeight; for (let y = 0; y < h; y += 300) { window.scrollTo(0, y); await new Promise(r => setTimeout(r, 90)); } }); await sleep(800); }
  // 1. tokens + global link easing + nav CSS state
  { const { page, ctx, errors } = await open('/about');
    const t = await page.evaluate(() => { const cs = getComputedStyle(document.documentElement); const a = document.querySelector('.footer a.footer-link, footer a'); const logo = document.querySelector('.thx-nav-logo'); const nav = document.getElementById('thx-nav'); const glass = document.querySelector('.thx-nav-glass'); const pin = document.querySelector('.thx-nav-panel-in'); return { ease: cs.getPropertyValue('--thx-ease').trim(), durFast: cs.getPropertyValue('--thx-dur-fast').trim(), linkT: a && getComputedStyle(a).transition, logoT: logo && getComputedStyle(logo).transition, navT: nav && getComputedStyle(nav).transition, glassT: glass && getComputedStyle(glass).transition, panelInT: pin && getComputedStyle(pin).transition, perWordPlates: document.querySelectorAll('#thx-nav .thx-nav-menu a[data-plate]').length, social: (() => { const s = document.querySelector('.footer-social-row a'); return s ? Math.round(s.getBoundingClientRect().width) : null; })() }; });
    check('EASE-06: easing/duration tokens live', (SPRING.test(t.ease) || /cubic-bezier\(\.22, ?1, ?\.36, ?1\)/.test(t.ease)) && t.durFast === '240ms', { ease: t.ease, durFast: t.durFast });
    check('EASE-05: footer links transition colour on the spring curve', t.linkT && SPRING.test(t.linkT) && /color 0\.24s/.test(t.linkT), t.linkT);
    check('EASE-02: nav logo transition includes transform (hover scale restored)', t.logoT && /transform/.test(t.logoT), t.logoT);
    check('EASE-01/SIG-05: no grid-template-rows/border-radius transition on the nav; sheet content moves on transform', t.navT && !/grid-template-rows|border-radius/.test(t.navT) && t.panelInT && /transform/.test(t.panelInT), { navT: t.navT, panelInT: t.panelInT });
    check('EASE-07: glass transitions no box-shadow', t.glassT && !/box-shadow/.test(t.glassT), t.glassT);
    check('SIG-01: no per-word plates in the markup', t.perWordPlates === 0, t.perWordPlates);
    check('RM-06: footer social anchors are 44px wide', t.social === 44, t.social);
    check('/about: no console/page errors', errors.length === 0, errors.slice(0, 3)); await ctx.close(); }
  // 2. Home: single entrance, no scroll reveals, press states
  { const { page, ctx, errors } = await open('/', { init: ANIM_INIT, settle: 2500 });
    const early = await page.evaluate(() => window.__anims.filter(a => !/hero-poster|hero-frame|hero-video|hero-ctrl/.test(a.sel)).length);
    await scrollAll(page);
    const a = await page.evaluate(() => ({ total: window.__anims.length, nonHero: window.__anims.filter(x => !/hero|thx-in|footer-wordmark|thx-grad/.test(x.sel) && !/opacity|transform/.test(x.prop || '') === false).filter(x => !/hero/.test(x.sel)).map(x => x.sel + ':' + (x.prop || x.via)).slice(0, 12), stuck: [...document.querySelectorAll('h1,h2,h3,p')].filter(e => !/hero-vletter|footer-lang-label/.test(e.className)).filter(e => { const cs = getComputedStyle(e); return parseFloat(cs.opacity) < 0.95 || (cs.clipPath && cs.clipPath !== 'none'); }).length, stuckEls: [...document.querySelectorAll('h1,h2,h3,p')].filter(e => !/hero-vletter|footer-lang-label/.test(e.className)).filter(e => { const cs = getComputedStyle(e); return parseFloat(cs.opacity) < 0.95 || (cs.clipPath && cs.clipPath !== 'none'); }).slice(0, 8).map(e => e.tagName + '.' + String(e.className).slice(0, 30) + '@' + getComputedStyle(e).opacity + '/' + getComputedStyle(e).clipPath.slice(0, 20)), rvh: document.querySelectorAll('.thx-rvH, [class*="thx-rv"]').length, lazy: document.querySelectorAll('img[loading="lazy"]').length }));
    check('REVEAL-01/02: no heading/section reveals on Home during a full scroll (nothing stuck at opacity<1 or clipped)', a.stuck === 0 && a.nonHero.filter(s => !/footer|thx-grad|hero|^CANVAS/.test(s)).length === 0, { stuck: a.stuck, stuckEls: a.stuckEls, sample: a.nonHero });
    // press states (ACT-01/02)
    const press = await page.evaluate(async () => { const card = document.querySelector('a.thxo-card'); const btn = document.querySelector('.hero-ctrl-btn'); const out = {}; if (card) { card.dispatchEvent(new MouseEvent('mousedown', { bubbles: true })); } return out; });
    const cardPress = await page.evaluate(async () => { const card = document.querySelector('a.thxo-card'); if (!card) return 'no-card'; const r = card.getBoundingClientRect(); return { x: r.x + r.width / 2, y: r.y + r.height / 2 }; });
    if (cardPress !== 'no-card') { await page.evaluate(() => document.addEventListener('click', e => e.preventDefault(), true)); await page.evaluate(c => window.scrollTo(0, window.scrollY + c.y - 300), cardPress); await sleep(400); const c2 = await page.evaluate(() => { const card = document.querySelector('a.thxo-card'); const r = card.getBoundingClientRect(); return { x: r.x + r.width / 2, y: r.y + r.height / 2 }; }); await page.mouse.move(c2.x, c2.y); await sleep(200); await page.mouse.down(); await sleep(120); const tr = await page.evaluate(() => getComputedStyle(document.querySelector('a.thxo-card')).transform); await page.mouse.up(); check('ACT-01/02: a card answers press with a transform while hovered', tr && tr !== 'none' && /0\.98/.test(tr), tr); }
    const hb = await page.evaluate(() => { const b = document.querySelector('.hero-ctrl-btn'); if (!b) return null; const r = b.getBoundingClientRect(); return { x: r.x + r.width / 2, y: r.y + r.height / 2 }; });
    if (hb) { await page.evaluate(() => window.scrollTo(0, 0)); await sleep(300); const hb2 = await page.evaluate(() => { const b = document.querySelector('.hero-ctrl-btn'); const r = b.getBoundingClientRect(); return { x: r.x + r.width / 2, y: r.y + r.height / 2 }; }); await page.mouse.move(hb2.x, hb2.y); await sleep(300); await page.mouse.down(); const trEarly = await page.evaluate(() => getComputedStyle(document.querySelector('.hero-ctrl-btn')).transform); await sleep(340); const tr = await page.evaluate(() => getComputedStyle(document.querySelector('.hero-ctrl-btn')).transform); await page.mouse.up(); check('ACT-02: hero control press wins over its hover transform (scale .97, settled after the 240 ms transition)', tr && /0\.97/.test(tr), { settled: tr, firstFrame: trEarly }); }
    check('/: no console/page errors', errors.length === 0, errors.slice(0, 3)); await ctx.close(); }
  // 3. article: no reveals, no autoplay, rail feedback, reduced-motion instant scroll
  { const { page, ctx, errors } = await open('/our-thinking/remove-the-creators-and-all-media-platforms-go-dark', { init: () => { window.__intervals = []; const oi = window.setInterval; window.setInterval = function (fn, ms) { window.__intervals.push(ms); return oi.apply(this, arguments); }; }, settle: 2500 });
    const art = await page.evaluate(() => ({ intervals5s: window.__intervals.filter(ms => ms >= 4000 && ms <= 6000).length, stuck: [...document.querySelectorAll('.thx-read-body p, .thx-read-body h2, .thx-read-body h3, .ethx-car')].filter(e => parseFloat(getComputedStyle(e).opacity) < 0.95).length, rvl: document.querySelectorAll('.xp-rvl, .ethx-rvl, [class*="xpRise"]').length, railT: (() => { const a = document.querySelector('nav.ethx-railnav a'); return a ? getComputedStyle(a).transition : null; })(), cardT: (() => { const c = document.querySelector('.thx-rel-card'); return c ? getComputedStyle(c).transition : null; })(), dotsBorder: (() => { const d = document.querySelector('.ethx-dot, .ethx-dots button, .ethx-dots span'); return d ? getComputedStyle(d).borderWidth : null; })() }));
    check('INV-03/ACT-08: no 5 s carousel autoplay interval', art.intervals5s === 0, art.intervals5s);
    check('REVEAL-03: article blocks visible at once, no reveal classes', art.stuck === 0 && art.rvl === 0, { stuck: art.stuck, rvl: art.rvl });
    check('ACT-03: section rail links carry a transition (hover/press feedback)', art.railT && art.railT !== 'all 0s ease 0s' && /opacity|transform/.test(art.railT), art.railT);
    check('EASE-07: related cards transition transform only (no box-shadow)', art.cardT && !/box-shadow/.test(art.cardT), art.cardT);
    const p11x = await page.evaluate(() => ({ heroAnim: [...document.querySelectorAll('.ethx-heroinner > *')].map(e => getComputedStyle(e).animationName), ctaMag: (() => { const b = document.querySelector('.ethx-cta .thxo-btn'); if (!b) return 'no-cta'; const r = b.getBoundingClientRect(); b.dispatchEvent(new PointerEvent('pointermove', { clientX: r.left + 4, clientY: r.top + 4, bubbles: true })); return b.style.transform || ''; })() }));
    check('REVEAL-04: hero text carries no xpRise entrance (template head override)', p11x.heroAnim.length > 0 && p11x.heroAnim.every(a => a === 'none'), p11x.heroAnim);
    check('INV-05: the CTA does not drift under the pointer (magnetic CTA removed, pubs-xp 1.4.1)', p11x.ctaMag === 'no-cta' || p11x.ctaMag === '', p11x.ctaMag);
    check('article: no console/page errors', errors.length === 0, errors.slice(0, 3)); await ctx.close(); }
  { const { page, ctx } = await open('/our-thinking/the-end-of-the-sponsorship-era', { ctx: { reducedMotion: 'reduce' }, settle: 2500 });
    const rm = await page.evaluate(async () => { const a = document.querySelector('.ethx-down, a.ethx-down'); if (!a) return 'no-arrow'; const y0 = window.scrollY; a.click(); await new Promise(r => requestAnimationFrame(() => requestAnimationFrame(r))); const y1 = window.scrollY; await new Promise(r => setTimeout(r, 400)); const y2 = window.scrollY; return { y0, y1, y2, instant: Math.abs(y2 - y1) < 2 && y1 !== y0 }; });
    check('RM-01: hero down-arrow jumps instantly under prefers-reduced-motion', rm === 'no-arrow' || rm.instant, rm); await ctx.close(); }
  // 4. scouting + cookies
  { const { page, ctx, errors } = await open('/scouting', { settle: 2500 });
    const sc = await page.evaluate(() => ({ all: [...document.querySelectorAll('.sc-chip, .sc-btn, .sc-input, .sc-select, #sc-submit')].map(e => getComputedStyle(e).transition).filter(t => /all/.test(t)).length, drop: (() => { const d = document.getElementById('sc-mediakit'); return d ? d.tagName : null; })() }));
    check('EASE-03: no transition:all on scouting controls', sc.all === 0, sc.all);
    const photoT = await page.evaluate(() => { const i = document.querySelector('.sc-photo img'); return i ? getComputedStyle(i).transition : 'no-photo'; });
    check('EASE-10: intro photo filter hover ≤ 420 ms on the spring curve (scouting 2.1.1)', photoT === 'no-photo' || (SPRING.test(photoT) && !/0\.55s|0\.5s|0\.6s|\b1s/.test(photoT)), photoT);
    await page.keyboard.press('Tab'); await sleep(6500); await page.keyboard.press('Tab'); await sleep(1500);
    const ck = await page.evaluate(() => { const b = document.querySelector('.thxck-banner'); const pref = b && b.querySelector('.thxck-link, button:last-child'); return { banner: !!b, bT: b && getComputedStyle(b).transition }; });
    check('ACT-06: cookie banner enters with a short spring transition', ck.banner && ck.bT && SPRING.test(ck.bT) && !/0\.5s|0\.6s|1s/.test(ck.bT), ck);
    check('/scouting: no console/page errors', errors.length === 0, errors.slice(0, 3)); await ctx.close(); }
  // 5. forced colors: footer swarm canvas hidden, hero controls opaque
  { const { page, ctx } = await open('/', { ctx: { forcedColors: 'active' }, settle: 2500 });
    await page.evaluate(() => window.scrollTo(0, document.documentElement.scrollHeight)); await sleep(1500);
    const fc = await page.evaluate(() => ({ canvas: (() => { const c = document.querySelector('[data-thx-anim="footer-wordmark"] canvas'); return c ? getComputedStyle(c).display : 'none-el'; })(), grad: (() => { const g = document.querySelector('[data-thx-anim="footer-wordmark"] .thx-grad'); return g ? getComputedStyle(g).opacity : null; })(), ctrl: (() => { const b = document.querySelector('.hero-ctrl-btn'); return b ? getComputedStyle(b).backgroundColor : null; })() }));
    check('RM-04: forced colours keep the text wordmark (canvas hidden)', fc.canvas !== 'block' && (fc.grad === null || parseFloat(fc.grad) === 1), fc);
    check('RM-07: hero controls opaque under forced colours', fc.ctrl && !/rgba\(255, 255, 255, 0\.\d/.test(fc.ctrl), fc.ctrl); await ctx.close(); }
  // 6. nav sheet on phone: tap→first change ≤ 100 ms
  { const { page, ctx } = await open('/about', { ctx: { ...devices['iPhone 13'] } });
    const sheet = await page.evaluate(async () => { const b = document.querySelector('.thx-nav-burger'); const pin = document.querySelector('.thx-nav-panel-in'); const tr0 = getComputedStyle(pin).transform; const t0 = performance.now(); b.click(); let first = null; for (let i = 0; i < 40; i++) { await new Promise(r => requestAnimationFrame(r)); const tr = getComputedStyle(pin).transform; if (tr !== tr0 && first === null) { first = performance.now() - t0; } } await new Promise(r => setTimeout(r, 500)); const open = document.getElementById('thx-nav').getAttribute('data-open'); const navT = getComputedStyle(document.getElementById('thx-nav')).transition; return { firstChangeMs: first === null ? null : Math.round(first), open, navT, from: tr0.slice(0, 30) }; });
    check('SIG-05/06: sheet opens on transform within 100 ms of the tap', sheet.open === 'true' && sheet.firstChangeMs !== null && sheet.firstChangeMs <= 100, sheet); await ctx.close(); }
  await browser.close();
  fs.writeFileSync(path.join(__dirname, '..', 'p11', (PROD ? 'p11_verify_prod.json' : 'p11_verify_staging.json')), JSON.stringify({ base: BASE, results, fails }, null, 1));
  console.log((fails ? fails + ' FAILURE(S)' : 'ALL PASS') + ' — ' + results.length + ' checks (' + BASE + ')'); process.exit(fails ? 1 : 0);
})();
