// Phase 3: section internals (padding/margin composition of every content gap) + baseline screenshots. Usage: node p3_measure.js [label] [cssfile]
const {chromium}=require('playwright');const fs=require('fs');
const label=process.argv[2]||'before', cssFile=process.argv[3]||null;
const OUT='/private/tmp/claude-501/-Users-x-CLAUDE/1f9ab44c-dab4-4c10-9374-4fb09761db8c/scratchpad/build/p3';
const PAGES=[['home','https://www.theodyx.com/'],['about','https://www.theodyx.com/about'],['capabilities','https://www.theodyx.com/our-capabilities'],['contact','https://www.theodyx.com/contact'],['thinking','https://www.theodyx.com/our-thinking']];
const VP=[['desktop',1440,900,false],['mobile',390,844,true]];
(async()=>{const b=await chromium.launch();const css=cssFile?fs.readFileSync(cssFile,'utf8'):null;const summary={};
for(const [vname,w,h,mob] of VP){for(const [key,url] of PAGES){
  const ctx=await b.newContext({viewport:{width:w,height:h},deviceScaleFactor:mob?2:1,isMobile:mob,hasTouch:mob,userAgent:mob?'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1':'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36'});
  const p=await ctx.newPage();await p.goto(url,{waitUntil:'load'});if(css)await p.addStyleTag({content:css});await p.waitForTimeout(1500);
  await p.evaluate(()=>{document.querySelectorAll('.thx-rvH,.thx-rvC,.thx-rvI').forEach(e=>e.classList.add('thx-on'));document.querySelectorAll('video').forEach(v=>{try{v.pause()}catch(e){}})});await p.waitForTimeout(300);
  const r=await p.evaluate(()=>{const px=v=>Math.round(parseFloat(v)||0);const secs=[...document.querySelectorAll('section.thxo-hero,section.thxo-sec,section.thxo-cta-band,section.hero,footer.footer,.thxo-titleblock,section.banner-sec > .page-wrapper > *:not(.thxo-root)')].filter(e=>e.getBoundingClientRect().height>0&&getComputedStyle(e).display!=='none');const rows=secs.map(s=>{const cs=getComputedStyle(s);const r=s.getBoundingClientRect();const kids=[...s.children].filter(k=>k.getBoundingClientRect().height>0);const f=kids[0],l=kids[kids.length-1];const fr=f&&f.getBoundingClientRect(),lr=l&&l.getBoundingClientRect();return {sel:(s.tagName+'.'+String(s.className).split(' ').filter(c=>!/^thx-(on|rv)/.test(c)).slice(0,2).join('.')).slice(0,36),top:Math.round(r.top+scrollY),h:Math.round(r.height),mt:px(cs.marginTop),mb:px(cs.marginBottom),pt:px(cs.paddingTop),pb:px(cs.paddingBottom),firstIn:f?Math.round(fr.top-r.top):null,lastIn:l?Math.round(r.bottom-lr.bottom):null,left:Math.round(r.left),cw:Math.round(r.width)}});const gaps=[];for(let i=1;i<rows.length;i++){gaps.push({from:rows[i-1].sel,to:rows[i].sel,contentGap:rows[i].top+rows[i].firstIn-(rows[i-1].top+rows[i-1].h-rows[i-1].lastIn),boxGap:rows[i].top-(rows[i-1].top+rows[i-1].h)})}return {rows,gaps}});
  summary[key+'.'+vname]=r;console.log(key,vname,'gaps',r.gaps.map(g=>g.contentGap).join('/'),'| boxes',r.rows.map(x=>x.sel.replace(/SECTION\.|DIV\.|FOOTER\./,'')+':mt'+x.mt+'/pt'+x.pt+'/pb'+x.pb+'/in'+x.firstIn+'-'+x.lastIn).join(' '));
  if(!(key==='contact'||key==='thinking'))await p.screenshot({path:`${OUT}/${label}-${key}-${vname}.png`,fullPage:true});
  await ctx.close();}}
fs.writeFileSync(`${OUT}/${label}.json`,JSON.stringify(summary,null,1));await b.close();})();
