// CPU profile of a page under 4x throttling (mobile) → hottest functions + long tasks + what sits under the nav
const {chromium}=require('playwright');
const url=process.argv[2]||'https://www.theodyx.com/about';
(async()=>{const b=await chromium.launch();const ctx=await b.newContext({viewport:{width:412,height:915},deviceScaleFactor:2,isMobile:true,hasTouch:true,userAgent:'Mozilla/5.0 (Linux; Android 11; moto g power (2022)) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Mobile Safari/537.36'});
const p=await ctx.newPage();await p.addInitScript(()=>{window.__lt=[];try{new PerformanceObserver(l=>{for(const e of l.getEntries())window.__lt.push({t:Math.round(e.startTime),d:Math.round(e.duration),a:(e.attribution||[]).map(x=>x.containerType+':'+(x.containerSrc||x.containerName||'').slice(0,40)).join(',')})}).observe({type:'longtask',buffered:true})}catch(e){}});
const c=await ctx.newCDPSession(p);await c.send('Emulation.setCPUThrottlingRate',{rate:4});await c.send('Profiler.enable');await c.send('Profiler.setSamplingInterval',{interval:500});await c.send('Profiler.start');
const t0=Date.now();await p.goto(url,{waitUntil:'load'});await p.waitForTimeout(7000);
const {profile}=await c.send('Profiler.stop');
const self={};const byId={};profile.nodes.forEach(n=>byId[n.id]=n);let t=0;profile.samples.forEach((id,i)=>{const d=profile.timeDeltas[i]||0;const n=byId[id];const cf=n.callFrame;const key=(cf.functionName||'(anon)')+' '+(cf.url||'').replace(/^https?:\/\//,'').replace(/.*\//,'').slice(0,40)+':'+cf.lineNumber;self[key]=(self[key]||0)+d});
const top=Object.entries(self).sort((a,b)=>b[1]-a[1]).slice(0,22).map(([k,v])=>Math.round(v/1000)+'ms '+k);
// inclusive time for nav.js: any sample whose stack contains theodyx-nav
const parent={};profile.nodes.forEach(n=>(n.children||[]).forEach(ch=>parent[ch]=n.id));let navInc=0,tot=0;profile.samples.forEach((id,i)=>{const d=profile.timeDeltas[i]||0;tot+=d;let n=id,hit=false;while(n){if((byId[n].callFrame.url||'').includes('theodyx-nav')){hit=true;break}n=parent[n]}if(hit)navInc+=d});
// inclusive per top-level nav.js function (functions in nav.js whose parent is not in nav.js)
const inc={};profile.samples.forEach((id,i)=>{const d=profile.timeDeltas[i]||0;let n=id,topNav=null;while(n){const u=byId[n].callFrame.url||'';if(u.includes('theodyx-nav'))topNav=byId[n].callFrame.functionName+':'+byId[n].callFrame.lineNumber;n=parent[n]}if(topNav)inc[topNav]=(inc[topNav]||0)+d});
const incTop=Object.entries(inc).sort((a,b)=>b[1]-a[1]).slice(0,10).map(([k,v])=>Math.round(v/1000)+'ms '+k);
const info=await p.evaluate(()=>{const nav=document.getElementById('thx-nav');const r=nav.getBoundingClientRect();nav.style.pointerEvents='none';const els=document.elementsFromPoint(r.left+r.width/2,r.top+r.height/2).slice(0,6).map(e=>e.tagName+'.'+String(e.className).slice(0,30)+(e.tagName==='IMG'?' '+e.naturalWidth+'x'+e.naturalHeight+' '+e.currentSrc.slice(-50):'')+(e.tagName==='VIDEO'?' '+e.videoWidth+'x'+e.videoHeight:''));nav.style.pointerEvents='';const N=window.__thxNav||{};return {lt:window.__lt,tickMs:N.tickMs,lens:N.lens,inks:N.inks,under:els,imgs:[...document.images].filter(i=>i.naturalWidth>1200).map(i=>i.naturalWidth+'x'+i.naturalHeight).slice(0,8)}});
console.log(url,'total sampled',Math.round(tot/1000),'ms; nav.js inclusive',Math.round(navInc/1000),'ms');console.log('SELF top:\n  '+top.join('\n  '));console.log('nav.js inclusive by entry fn:\n  '+incTop.join('\n  '));console.log('long tasks:',JSON.stringify(info.lt));console.log('tickMs',info.tickMs,'lens',info.lens,'inks',info.inks);console.log('under nav:',info.under.join(' | '));console.log('big imgs:',info.imgs.join(' '));await b.close();})().catch(e=>{console.error(e);process.exit(1)});
